### ISSUE TITLE
`import` CLI command stores empty raw emails in db.

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#316]
When the CLI cmd `import` imports emails from mbox, raw_messages are created in cassandra, but all properties are null, except `raw_msg_id`.

**Comment by gdchamal** [comment]
Yes of course @sapiens-sapide as you changed the column naming of RawMessage to something different on golang side, the RawMessage.create methode of core object does not work anymore.

so column naming MUST BE for RawMessage cassandra model:
- data instead of raw_data (we know it's a raw don't repeat this naming in column)
- size instead of raw_size (same logic than previous comment)

raw_msg_id is not correct naming from my POV, it should be (as it was before) raw_id.
