### ISSUE TITLE
Missing properties when saving Message in delivery process

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#318]
`qualifier.py` saves incomplete Message in db & index.  

Missing properties : 

* date_insert
* raw_msg_id

**Comment by gdchamal** [comment]
date_insert value does not have to be set by processing layer but the store one (the previous default value set by CoreMessage.create is no more)

raw_msg_id was missing in NewMessage parameter structure I add it and will set this value.

Need to rework the BaseRawParser class to be initialized with the whole RawMessage instead of only the body
