### ISSUE TITLE
Can't reply to a message within discussion context

### ISSUE THREAD

**Issue by sapiens-sapide** [CaliOpen/Caliopen#505]
Within the tab of a discussion, trying to compose a reply at the botton of messages list, the save/send actions failed with the following error : 422
```
"list of participants is not consistent for this discussion"
``` 

Need to investigate.

**Comment by iamdey** [comment]
I think it is related to the depreciation of discussion api:

On the client, with last night PR, I build the participants from the last received message (actually the message in reply to). So this happened.

**Comment by iamdey** [comment]
Due to inconsistencies in mail protocol (someone can change participants in a discussion) so we can't use a in-reply message to calc participants.

We have 2 solutions so:

* we don't completely deprecate `api/discussions/*` (because I won't load aaaaaallll messages of a discussion to calc participants)
* or it is the responsibility of the backend to calc participants (it is almost the case right ?)

I try this to see if it works

**Comment by iamdey** [comment]
second solution doesn't work right now, I'm trying to POST the draft with participants at all and it fails with the 422 error.

**Comment by iamdey** [comment]
example of POST payload:*

```json
{
	"subject": "Re: Syntax tables for multiple modes [was: bug#22983: syntax-ppss\n returns wrong result.]",
	"body": "foobar",
	"identities": [{
		"identifier": "dev@caliopen.local",
		"type": "email"
	}],
	"discussion_id": "3c985512-d9b0-4fa8-8d2e-5ba30e086b0e"
}
```
