### ISSUE TITLE
"reply" button nonfunctional

### ISSUE THREAD

**Issue by VincentJ-Caliopen** [CaliOpen/Caliopen#894]
While in a discussion, hitting _reply_ on a message doesn't do anything. 
_#reply_ get added at the end of the adress bar, but nothing happen inside the page.
I believe the page should scroll down to the reply box, with the selected message in quote?

![capture du 2018-05-03 12-42-34](https://user-images.githubusercontent.com/38942789/39572695-80d41f0a-4ed0-11e8-9677-0d0d36d5c977.png)

linked to #521

**Comment by iamdey** [comment]
Yes the reply button should scroll but the functionality didn't work well so we reverted it and waiting for the next specifications of the timeline/discussions (/cc @Lauth0)

In fact reply button also change the parent of a reply and add an excerpt of the message in the form when the message isn't the last one (by default the parent is always the last one) but this might not works well due to error in the sort algorithm when rendering the discussion (/cc @sapiens-sapide).

I need to make sure what works and whet doesn't and maybe close this afterward.

**Comment by sapiens-sapide** [comment]
@iamdey : what kind of errors in the sort algorithm ? Could you describe, so we could patch algo if needed. Thanks.

**Comment by iamdey** [comment]
if I'm right a reply is displayed before the message instead of after
(check with a full page reload)
