### ISSUE TITLE
Add device verification

### ISSUE THREAD

**Issue by VincentJ-Caliopen** [CaliOpen/Caliopen#899]
It is currently not possible to verify a device. 
As such If I'm not using the device I first used with version 0.9.0 (when device management happened), the device page will appear on every single login. 
As I cannot verify my device I cannot do anything about this, which is very frustrating.

Could we disable device management until device verification becomes possible?

**Comment by Peh4** [comment]
Same here, perhaps because of Firefox updates.
I'm stuck into new device verification

Old verified device : 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0

New restricted device : 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:63.0) Gecko/20100101 Firefox/63.0

**Comment by iamdey** [comment]
you should not be "stuck", we didn't use the device verification since we don't have a consistent device recognition. You just have to change the page and just omit the verification message

**Comment by Peh4** [comment]
@iamdey something else is going wrong with my emails so
i've three accounts set and nothing is loading

**Comment by iamdey** [comment]
We have problems with worker, we are actively working on this. It's not
related to devices.
It will be ok asap, thnk you for your patience.

**Comment by iamdey** [comment]
device verfication has been implemented
